/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uja.ssmmaa.curso2021.practica2_multiagentes.gui;

import com.uja.ssmmaa.curso2021.practica2_multiagentes.agentes.AgenteComprador;
import com.uja.ssmmaa.curso2021.practica2_multiagentes.util.Pedido;


/**
 *
 * @author ghutt
 */
public class CompradorJFrame extends javax.swing.JFrame {
    private final AgenteComprador myAgent;
    private OkCancelDialog finalizacion;
    /**
     * Creates new form CompradorJFrame
     */
    public CompradorJFrame(AgenteComprador myAgent) {
        super(myAgent.getName());
        initComponents();
        this.myAgent=myAgent;
    }
     /**
     * Método para activar el botón de enviar si hay agentes operación
     * disponibles
     * @param activar
     */
    public void activarEnviar(boolean activar) {
        botonEnviar.setEnabled(activar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaChicle = new javax.swing.JLabel();
        cantidadCaramelos = new javax.swing.JTextField();
        cantidadGominolas = new javax.swing.JTextField();
        cantidadChicles = new javax.swing.JTextField();
        botonEnviar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        etiquetaCaramelos = new javax.swing.JLabel();
        etiquetaGominola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        etiquetaChicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaChicle.setText("Chicles");

        cantidadCaramelos.setText("0");

        cantidadGominolas.setText("0");

        cantidadChicles.setText("0");

        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        Titulo.setText("Elige cuantos productos");

        etiquetaCaramelos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCaramelos.setText("Caramelos");

        etiquetaGominola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaGominola.setText("Gominolas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cantidadGominolas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaGominola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cantidadChicles)
                    .addComponent(etiquetaChicle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cantidadCaramelos)
                    .addComponent(etiquetaCaramelos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonEnviar)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaChicle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCaramelos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaGominola, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadCaramelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadChicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadGominolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(botonEnviar)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        Pedido pedido;
        pedido=new Pedido();
        
        pedido.setCantidadCaramelos(Integer.parseInt(cantidadCaramelos.getText()));
        pedido.setCantidadChicles(Integer.parseInt(cantidadChicles.getText()));
        pedido.setCantidadGominolas(Integer.parseInt(cantidadGominolas.getText()));
        
        myAgent.enviarPedido(pedido);
    }//GEN-LAST:event_botonEnviarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        finalizacion = new OkCancelDialog(this, true, myAgent);
        finalizacion.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JTextField cantidadCaramelos;
    private javax.swing.JTextField cantidadChicles;
    private javax.swing.JTextField cantidadGominolas;
    private javax.swing.JLabel etiquetaCaramelos;
    private javax.swing.JLabel etiquetaChicle;
    private javax.swing.JLabel etiquetaGominola;
    // End of variables declaration//GEN-END:variables
}
